project:
  type: website
  output-dir: docs

website:
  title: "Coe College Tree Archive"
  favicon: "images/logo.png"
  open-graph: true
  google-analytics: 
    tracking-id: "G-3XLB5C4Z3N"
    anonymize-ip: true
    storage: none
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: About
      - text: "Tree Map"
        file: tree-map.qmd
      - text: "Tree Profiles"
        file: tree-profiles.qmd
      - text: "Data"
        file: data.qmd
      - text: "Identification"
        file: identification.qmd
      - text: "Contribute"
        file: contribute.qmd
      - text: "Connect"
        file: connect.qmd

format:
  html:
    theme: 
      - mint
      - custom.scss
    fontsize: 1.1rem
    fontcolor: "#666666"
    linkcolor: "#89b04c"
    css: styles.css
    toc: true

editor: visual