---
title: "**Data**"
---

------------------------------------------------------------------------

Data collection and access are central to the objective of the Coe College Tree Archive. By gathering data on the College's trees and making these data easy to access, the project preserves a record of these trees for the future and supports the work of others interested in our community's environment. Explore these data through interactive tables and charts, by downloading the data, or by reading the full report on Coe's trees.

<br>

------------------------------------------------------------------------

<center>

[367,000 pounds]{style="font-size: 3rem; color: #89b04c; font-weight: bold"}

The total carbon sequestered by trees on the west side of Coe's campus

</center>

------------------------------------------------------------------------

<center>

[5,500 pounds]{style="font-size: 3rem; color: #89b04c; font-weight: bold"}

The additional carbon sequestered by trees on the west side of Coe's campus every year

</center>

------------------------------------------------------------------------

<center>

[61,000 gallons]{style="font-size: 3rem; color: #89b04c; font-weight: bold"}

The annual water runoff avoided from trees on the west side of Coe's campus

</center>

------------------------------------------------------------------------

<center>

[324 pounds]{style="font-size: 3rem; color: #89b04c; font-weight: bold"}

The annual removal of hazardous ambient air pollutants from trees on the west side of Coe's campus

</center>

------------------------------------------------------------------------

<br>

## **How Do We Estimate The Benefits of Trees?**

During the Fall 2022 semester, trees on the west side of of campus were identified, measured, and photographed. The primary records for each tree are its species and its [diameter at breast height (DBH)](https://www.portland.gov/trees/tree-care-and-resources/how-measure-tree), as these two fields are important determinants of other physical characteristics such as the tree's biomass.

After reviewing these data for accuracy, they were passed along to [i-Tree Eco](https://www.itreetools.org/about), a software for analyzing urban forests developed by the US Forest Service in collaboration with a host of other public and private partners. This software uses statistical models that have been calibrated on other trees from around the world to predict key features of the trees here at Coe. To estimate social benefits, these models incorporate local data on air pollution, precipitation, and the population. Those interested in the details of this process are encouraged to review the [documentation for i-Tree Eco](https://www.itreetools.org/support/resources-overview/i-tree-methods-and-files).

<br>

## **View the Tree Data**

The easiest way to view the Coe College Tree Archive dataset is in your browser through the interactive data table. The table allows you to view the full dataset used throughout the website without downloading the data. Interactive features of the table allow you to filter and sort the dataset as well.

<center><a class="button" href="https://coetreearchive.github.io/view-data/interactive-table.html">View Data Tables</a></center>

<br>

## **Download the Tree Data**

A central goal of the Coe College Tree Archive is to make engaging with Coe's natural environmental easier, both for current members of Coe's community and for future members of Coe's community. The tree data collected through this project offer a snapshot in time of the trees on our campus. To ensure anyone interested in our trees can easily explore this snapshot, data files from the project are available below as an Excel file, shapefiles (easiest for mapping in R and Python), and .kml (easiest for mapping in Google Earth).

<center>

<a class="button" href="https://github.com/CoeTreeArchive/CoeTreeArchive.github.io/raw/main/data/coe-tree-archive-all-years.xlsx">Download All Tree Data (Excel)</a>

<a class="button" href="https://github.com/CoeTreeArchive/CoeTreeArchive.github.io/raw/main/data/Fall%202022/cleaned-data/coe-tree-archive.zip">Download Fall 2022 Shapefile</a>

<a class="button" href="https://github.com/CoeTreeArchive/CoeTreeArchive.github.io/raw/main/data/Fall%202022/cleaned-data/coe-tree-archive.kml">Download Fall 2022 .kml</a>

</center>

<br>

Alternatively, you can access the Coe College Tree Archive data within your R or Python program by copying the code in the panel below. If you are interested in accessing additional data from the project (e.g., the full set of images, code to reproduce the website) visit [the Coe College Tree Archive's GitHub repository linked here](https://github.com/CoeTreeArchive/CoeTreeArchive.github.io). Data cleaning and visualization were done in the R programming language and the website itself was built using Quarto, a markdown language developed by Posit. All software used in the project are open source and available for free.

::: panel-tabset
## R

``` r
my_dir <- "https://github.com/CoeTreeArchive/CoeTreeArchive.github.io/raw/main"

# Read the Excel file with all data
library(openxlsx)

df <- read.xlsx(paste(my_dir, "/data/coe-tree-archive-all-years.xlsx", sep=""))

# Read shapefile with most recent data
library(sf)

temp <- tempfile()
download.file(
  paste(my_dir, "/data/Fall%202022/cleaned-data/coe-tree-archive.zip", sep=""),
  temp)
shp <- read_sf(unzip(temp, "coe-tree-archive.shp"))
unlink(temp)
```

## Python

``` python
my_dir = 'https://github.com/CoeTreeArchive/CoeTreeArchive.github.io/raw/main/'

# Read the Excel file with all data
import pandas as pd

df = pd.read_excel(my_dir + "data/coe-tree-archive-all-years.xlsx")

# Read shapefile with most recent data
import requests, zipfile, io
import geopandas as gpd

url = my_dir + 'data/Fall%202022/cleaned-data/coe-tree-archive.zip'
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()
shp = gpd.read_file('coe-tree-archive.shp')
```
:::

<br>

## **Read the Full Report**

Environmental benefit estimates come from the US Forest Service's i-Tree Eco tool. In addition to data files with these estimates, the i-Tree Eco generates a report summarizing key data. Read or download the report below to learn more about Coe's trees, the methodology for estimating environmental benefits, and view additional statistics.

<object data="/data/Fall 2022/cleaned-data/Fall-2022-written-report.pdf" type="application/pdf" width="100%" height="500px">

<p>Unable to display PDF file. <a  href="/data/Fall 2022/cleaned-data/Fall-2022-written-report.pdf">Download</a> instead.</p>

</object>
