---
title: "**Get Connected**"
---

<br>

## **Have Something to Share About Our Trees?**

Do you have a story related to a tree on Coe's campus you'd be comfortable sharing? Maybe just a picture with one of our trees? Whether you have a tree on campus that you're fond of for no particular reason, an amusing anecdote involving one of our trees, or a nostalgic memory of planting a tree after the 2020 derecho, we want to hear it! Numerical measurements can give us great insight into the physical impact of our trees, but your stories are the best way for us to understand just how valuable trees are in our personal lives and social systems.

If you have something (some words or a photo) you'd be willing to share, please consider contributing to the Coe Tree Archive. We will preserve what you submit alongside the other records maintained in the Coe Tree Archive, just click the button below.

<center><a class="button" href="https://forms.gle/6acapE5m9WgEFQmp6">Say Something About Our Trees!</a></center>

<br>

## **Interested in Connecting More With Your Environment?**

There are many ways in which you can use your talents, your time, your financial resources, and your voice to support local trees. See the list below for some ideas on steps you can take to get connected to tree and environmental life around our community.

<br>

### **Help Identify Trees in Your Community**

Identifying the trees in your community is not only a fun way to connect with the natural world in your everyday life, but an activity with the potential to meaningfully benefit your community. Paying close attention to the trees around can help catch damaging insect infestation early on---mitigating damages to tree life. It can also help identify threats that tree limbs might pose to people or buildings before these limbs fall in a storm. Lastly, identifying trees and helping others learn about the trees in their communities can inspire greater attitudes of sustainability in others. Connecting the people around you with the trees around both of you is a great way to build a passion for the natural world.

In its current state, the Coe Tree Archive only covers trees west of College Drive. A natural extension would be to cover Coe's campus East of College Drive. You might also consider revisiting trees on the West side of campus, making sure that the trees are correctly identified and that the online list is comprehensive. If you find any errors, have any updates, or would like to expand the archive please reach out to the project maintainer, Evan Perry, at [coe.tree.archive\@gmail.com](mailto:coe.tree.archive@gmail.com).

<br>

### **Take Advantage of Environmental Opportunities on Campus**

If you are interested in both connecting with the environment and connecting with other college students interested in the environment, then one of Coe's environmental groups might be a great fit. Environmental Club, or E-Club as it is more commonly known, has a great history of tackling environmental causes and projects both around campus, and in our wider Cedar Rapids community. Check your Coe email to get connected with E-Club.

<br>

### **Support ReLeaf Cedar Rapids**

Are you interested in planting trees or supporting local tree planting efforts? Consider supporting [ReLeaf Cedar Rapids](https://www.cedar-rapids.org/residents/parks_and_recreation/releaf_cedar_rapids_.php). ReLeaf Cedar Rapids is a project partnership between the City of Cedar Rapids and the nonprofit group Tree's Forever. The project's website contains resources to help all individuals contribute to the effort to rebuild Cedar Rapids' natural infrastructure following the derecho in Fall 2020. To learn more about where to make financial contributions, how to volunteer, and how to become a designated Tree Keeper, [click the link here](https://www.cedar-rapids.org/residents/parks_and_recreation/how_can_i_help_/index.php).

<br>
